version: "3.8"
services: 
  ubuntu:
    image: img1
    container_name: c1
    ports: 
    - "8763:80"
    volumes:
    - vol1:/data
    networks:
    - net1

volumes:
  vol1:
networks:
  net1:
    driver: bridge
